name: Run cargo tests
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/test.yml'
      - 'src/**/*.rs'
      - 'build.rs'
      - 'Cargo.toml'
      - '.cargo/**/*'
      - 'tests/**/*'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'src/**/*.rs'
      - 'build.rs'
      - 'Cargo.toml'
      - '.cargo/**/*'
      - 'tests/**/*'
env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 0
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1
      - name: Run tests
        run: |
          cargo test --verbose
  check-no-std:
    name: Check no-std
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v1
      - name: Run checks
        run: |
          cargo check --no-default-features
